[package]
name = "mcwv-core"
version = "1.0.0"
edition = "2021"

[lib]
name = "mcwv_core"
crate-type = ["staticlib"]

[dependencies]
sha2 = { version = "0.10", features = ["std"] }
hmac = { version = "0.12", features = ["std"] }
digest = { version = "0.10", features = ["std"] }

[profile.release]
panic = "abort"
lto = false
opt-level = "z"
strip = true
